/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import config.dbConnector;
import internalPages.departmentPage;
import internalPages.studentPage;
import internalPages.usersPage;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class deptForm extends javax.swing.JFrame {

    /**
     * Creates new form studentForm
     */
    public deptForm() {
        initComponents();
        
    }
    
    public void close(){
     this.dispose();
     dashBoard dash= new dashBoard();
     dash.setVisible(true);
     departmentPage up= new departmentPage();
     dash.maindesktop.add(up).setVisible(true);
    }
    int validateRegister(){
        int result;
        if(d_code.getText().isEmpty()||d_descrip.getText().isEmpty()){ 
  
       result=0;
       } else{
            result=1;
        }
        return result;
    }
    
    Color navcolor=new Color (255,153,0);
    Color headcolor=new Color(255,204,51);
    Color bodycolor=new Color (255,51,51);
    
    
    public String action;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        st_label = new javax.swing.JLabel();
        d_code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        s_id = new javax.swing.JLabel();
        d_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        d_descrip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("DEPARTMENT FORM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 0, 250, 40);

        close.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close);
        close.setBounds(460, 0, 30, 40);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 40));

        add.setBackground(new java.awt.Color(255, 153, 0));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("LABEL");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, -1));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 110, 40));

        d_code.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        d_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d_code.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d_code.setOpaque(false);
        jPanel1.add(d_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Department Code:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 30));

        s_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        s_id.setText("Department I.D:");
        jPanel1.add(s_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 30));

        d_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        d_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d_id.setEnabled(false);
        d_id.setOpaque(false);
        d_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_idActionPerformed(evt);
            }
        });
        jPanel1.add(d_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 280, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Department Description:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, 30));

        d_descrip.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        d_descrip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d_descrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        d_descrip.setOpaque(false);
        jPanel1.add(d_descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 280, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void d_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_idActionPerformed

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
     if(action.equals("Add")){
            
     int check=validateRegister();
     if(check==1){
         dbConnector dbc=new dbConnector();
            int result=dbc.insertData("INSERT INTO tbl_department(dept_code,dept_desc)VALUES('"+d_code.getText()+"','"+d_descrip.getText()+"')");
            if(result==1){
                JOptionPane.showMessageDialog(null,"Successfully Save!");
                close();
            }else{
                System.out.println("Saving Data Failed!");
            }
     }else{
         JOptionPane.showMessageDialog(null, "All fields are required!");
     }
            
        }else if(action.equals("Update")){
            dbConnector dbc=new dbConnector();
            dbc.updateData("UPDATE tbl_department SET dept_code='"+d_code.getText()+"',dept_desc='"+d_descrip.getText()+"'WHERE dept_id='"+d_id.getText()+"'");
            close();
        }else{
            JOptionPane.showMessageDialog(null,"No Action Selected!");
            close();
        }
    }//GEN-LAST:event_addMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        close();
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deptForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JLabel close;
    public javax.swing.JTextField d_code;
    public javax.swing.JTextField d_descrip;
    public javax.swing.JTextField d_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel s_id;
    public javax.swing.JLabel st_label;
    // End of variables declaration//GEN-END:variables
}
