/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import config.dbConnector;
import internalPages.studentPage;
import internalPages.usersPage;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author College-PC
 */
public class reportsForm extends javax.swing.JFrame {

    
    
    public reportsForm() {
        initComponents();
        labels.setVisible(false);
    }
public String unm;
public String actions;
public String klee="";
    
    public void close(){   
        this.dispose();
        main m = new main();
        m.setVisible(true);
        soldProduct up = new soldProduct();
        m.despane.add(up).setVisible(true);
        m.name.setText(unm);
        up.report = unm;
}
    
    public void dis(){
        if(klee.equals("Complete")){
            
            t_stat.setVisible(false);
            save.setVisible(false);
            jLabel6.setVisible(false);
            adfish.setVisible(false);
            labels.setVisible(true);
            jLabel14.setVisible(false);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fna = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        save = new javax.swing.JPanel();
        save1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        delete3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        st_address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dept = new javax.swing.JTextField();
        deptcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        t_stat = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fna.setBackground(new java.awt.Color(255, 204, 51));
        fna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Transaction I.D:");
        fna.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Last Name :");
        fna.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 30));

        lname.setEditable(false);
        lname.setBackground(new java.awt.Color(204, 204, 204));
        lname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fna.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Student Address:");
        fna.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, 30));

        tid.setEditable(false);
        tid.setBackground(new java.awt.Color(204, 204, 204));
        tid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        fna.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 190, 30));

        save.setBackground(new java.awt.Color(255, 153, 0));
        save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        save1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save1.setText("Save");
        save.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 30));

        fna.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 70, 30));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(null);

        date.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        date.setText("     ");
        jPanel3.add(date);
        date.setBounds(530, 10, 110, 30);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setText("Date :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(430, 10, 60, 30);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setText("Transactions:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 10, 290, 30);

        fna.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 50));

        delete3.setBackground(new java.awt.Color(255, 153, 0));
        delete3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delete3MouseExited(evt);
            }
        });
        delete3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cancel");
        delete3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 30));

        fna.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 70, 30));

        st_address.setEditable(false);
        st_address.setBackground(new java.awt.Color(204, 204, 204));
        st_address.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        st_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        st_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fna.add(st_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Department:");
        fna.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 110, 30));

        dept.setEditable(false);
        dept.setBackground(new java.awt.Color(204, 204, 204));
        dept.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dept.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fna.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 190, 30));

        deptcode.setEditable(false);
        deptcode.setBackground(new java.awt.Color(204, 204, 204));
        deptcode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deptcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deptcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fna.add(deptcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 190, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Department Code:");
        fna.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 110, 30));

        email.setEditable(false);
        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fna.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 190, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Transaction Status :");
        fna.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("First Name:");
        fna.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 30));

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(204, 204, 204));
        fname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fna.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, 30));

        t_stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Complete", " " }));
        fna.add(t_stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 190, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Email:");
        fna.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 80, 30));

        getContentPane().add(fna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 670, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Color bodycolor = new Color(153,204,255);
    Color headcolor = new Color(255,153,153);
    Color hover = new Color(0,153,204);
    
    
    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        dbconnect dbc = new dbconnect();
        if(actions.equals("Update")){
            int num = dbc.updateData("UPDATE `tbl_soldproduct` SET `f_code`='"+fname.getText()
                    +"',`u_id`='"+dept.getText()+"',`sp_status`='"+t_stat.getSelectedItem()+"' WHERE `sp_id`='"+tid.getText()+"'");

            if(num == 0){

            }else{
                JOptionPane.showMessageDialog(null, "Updated Successfully!");
                close();
                
            }

        }else if(actions.equals("Add")){

            if(fname.getText().isEmpty()||dept.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "All field must be inputed!! ");
                
            }
            else{
                dbc.insertData("INSERT INTO tbl_soldproduct (`f_code`, `u_id`, sp_date,`sp_status`) "

                    + "VALUES ('"+fname.getText()+"', '"+dept.getText()+"', CURDATE() ,'Pending')");
                JOptionPane.showMessageDialog(null,"Successfull added");

                close();
            }

        }
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setBackground(bodycolor);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save.setBackground(headcolor);
    }//GEN-LAST:event_saveMouseExited

    private void delete3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete3MouseClicked
       close();
    }//GEN-LAST:event_delete3MouseClicked

    private void delete3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete3MouseEntered
        delete3.setBackground(bodycolor);
    }//GEN-LAST:event_delete3MouseEntered

    private void delete3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete3MouseExited
        delete3.setBackground(headcolor);
    }//GEN-LAST:event_delete3MouseExited

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      dis();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel date;
    private javax.swing.JPanel delete3;
    public javax.swing.JTextField dept;
    public javax.swing.JTextField deptcode;
    public javax.swing.JTextField email;
    private javax.swing.JPanel fna;
    public javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField lname;
    private javax.swing.JPanel save;
    public javax.swing.JLabel save1;
    public javax.swing.JTextField st_address;
    public javax.swing.JComboBox<String> t_stat;
    public javax.swing.JTextField tid;
    // End of variables declaration//GEN-END:variables
}
