/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import config.dbConnector;
import internalPages.studentPage;
import internalPages.usersPage;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class userForms extends javax.swing.JFrame {

    /**
     * Creates new form studentForm
     */
    public userForms() {
        initComponents();
        
    }
    
    public void close(){
     this.dispose();
     dashBoard dash= new dashBoard();
     dash.setVisible(true);
     usersPage up= new usersPage();
     dash.maindesktop.add(up).setVisible(true);
    }
    int validateRegister(){
        int result;
        if(u_fname.getText().isEmpty()||u_lname.getText().isEmpty()||u_email.getText().isEmpty()||u_username.getText().isEmpty()||u_password.getText().isEmpty()){ 
  
       result=0;
       } else{
            result=1;
        }
        return result;
    }
    
    Color navcolor=new Color (255,153,0);
    Color headcolor=new Color(255,204,51);
    Color bodycolor=new Color (255,51,51);
    
    
    public String action;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        st_label = new javax.swing.JLabel();
        u_fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        s_id = new javax.swing.JLabel();
        u_id = new javax.swing.JTextField();
        u_lname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        st_lname1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        u_email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        u_username = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        u_password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("USER FORM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 0, 250, 40);

        close.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close);
        close.setBounds(310, 0, 30, 40);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        add.setBackground(new java.awt.Color(255, 153, 0));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("LABEL");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 20));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, 40));

        u_fname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        u_fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u_fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u_fname.setOpaque(false);
        jPanel1.add(u_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        s_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        s_id.setText("User I.D:");
        jPanel1.add(s_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 30));

        u_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        u_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u_id.setEnabled(false);
        u_id.setOpaque(false);
        u_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_idActionPerformed(evt);
            }
        });
        jPanel1.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, 30));

        u_lname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        u_lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u_lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u_lname.setOpaque(false);
        jPanel1.add(u_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Last Name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Last Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        st_lname1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        st_lname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        st_lname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        st_lname1.setOpaque(false);
        jPanel1.add(st_lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("E-mail:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 30));

        u_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        u_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u_email.setOpaque(false);
        jPanel1.add(u_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setText("Username:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));

        u_username.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        u_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u_username.setOpaque(false);
        jPanel1.add(u_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 200, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Password:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        u_password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        u_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        u_password.setOpaque(false);
        jPanel1.add(u_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void u_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_idActionPerformed

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
     if(action.equals("Add")){
            
     int check=validateRegister();
     if(check==1){
         dbConnector dbc=new dbConnector();
            int result=dbc.insertData("INSERT INTO tbl_user(user_fname,user_lname,user_email,u_username,u_password,user_status)VALUES('"+u_fname.getText()+"','"+u_lname.getText()+"','"+u_email.getText()+"','"+u_username.getText()+"','"+u_password.getText()+"','Pending')");
            if(result==1){
                JOptionPane.showMessageDialog(null,"Successfully Save!");
                close();
            }else{
                System.out.println("Saving Data Failed!");
            }
     }else{
         JOptionPane.showMessageDialog(null, "All fields are required!");
     }
            
        }else if(action.equals("Update")){
            dbConnector dbc=new dbConnector();
            dbc.updateData("UPDATE tbl_user SET user_fname='"+u_fname.getText()+"',user_lname='"+u_lname.getText()+"',user_email='"+u_email.getText()+"',u_username='"+u_username.getText()+"',u_password='"+u_password.getText()+"'WHERE user_id='"+u_id.getText()+"'");
            close();
        }else{
            JOptionPane.showMessageDialog(null,"No Action Selected!");
            close();
        }
    }//GEN-LAST:event_addMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        close();
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userForms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel s_id;
    public javax.swing.JLabel st_label;
    public javax.swing.JTextField st_lname1;
    public javax.swing.JTextField u_email;
    public javax.swing.JTextField u_fname;
    public javax.swing.JTextField u_id;
    public javax.swing.JTextField u_lname;
    public javax.swing.JTextField u_password;
    public javax.swing.JTextField u_username;
    // End of variables declaration//GEN-END:variables
}
